export type SubjectGroup = {
  name: string;
  description: string;
  topics: string[];
};

export type ExamTrack = {
  slug: string;
  name: string;
  audience: string;
  subjects: SubjectGroup[];
};

export type MockTestItem = {
  slug: string;
  exam: string;
  track: string;
  subject: string;
  name: string;
  questions: number;
  duration: string;
  access: "Free" | "Premium";
  type: "Full mock" | "Subject test" | "Topic test" | "Section test";
  description?: string;
  bannerImageUrl?: string;
};

export function formatTestType(val?: string): string {
  if (!val) return "Full mock";
  const lower = val.toLowerCase().trim();
  if (lower.includes("subject")) return "Subject test";
  if (lower.includes("section")) return "Sectional drill";
  if (lower.includes("topic") || lower.includes("chapter")) return "Chapter test";
  if (lower.includes("pyq") || lower.includes("previous")) return "Previous Year Paper";
  if (lower.includes("live")) return "Live Test";
  if (lower.includes("mini")) return "Mini Mock";
  return "Full mock";
}

export function normalizeTestType(val?: string): string {
  if (!val) return "full";
  const lower = val.toLowerCase().trim();
  if (lower.includes("subject")) return "subject";
  if (lower.includes("section")) return "section";
  if (lower.includes("topic") || lower.includes("chapter")) return "topic";
  if (lower.includes("pyq") || lower.includes("previous")) return "pyq";
  if (lower.includes("live")) return "live";
  if (lower.includes("mini")) return "mini";
  return "full";
}

const languages = [
  "Grammar & language use",
  "Vocabulary & Synonyms/Antonyms",
  "Prose & poetry comprehension",
  "Literary history & movements",
  "Authors, poets & prescribed texts",
  "Sentence correction & syntax",
];

const socialScience = [
  "Ancient, Medieval & Modern Indian History",
  "Physical, Regional & Indian Geography",
  "Indian Constitution, Governance & Political Science",
  "Micro & Macro Economics, Indian Economic Planning",
];

const commonTeaching = [
  "Teaching & learning methods",
  "Lesson planning & pedagogy",
  "Classroom management",
  "Assessment, evaluation & continuous learning",
  "Inclusive education & special needs",
  "Educational psychology & learner development",
];

export const syllabusTracks: Record<string, ExamTrack[]> = {
  "bpsc-tre-4": [
    {
      slug: "primary-1-5",
      name: "Classes 1–5 (Primary)",
      audience: "Primary teacher recruitment (PRT)",
      subjects: [
        {
          name: "Language (Qualifying)",
          description: "Part-I: English (mandatory) + Hindi / Urdu / Bengali language comprehension and functional grammar",
          topics: languages,
        },
        {
          name: "Elementary Mathematics",
          description: "Number system, fractions, decimals, percentage, profit & loss, ratio, geometry, and mensuration",
          topics: [
            "Number system & simplification",
            "Fractions & decimals",
            "Ratio & proportion",
            "Percentage & profit/loss",
            "Simple & compound interest",
            "Time, work & distance",
            "Geometry & basic mensuration",
            "Data handling & basic probability",
          ],
        },
        {
          name: "General Studies",
          description: "Core GS covering Bihar GK, General Science, Indian National Movement, Geography & Environment",
          topics: [
            "Bihar history, culture & geography",
            "General Science (Physics, Chemistry, Biology)",
            "Indian National Movement (1857 to 1947)",
            "Geography & environmental ecology",
            "Mental ability, reasoning & numerical aptitude",
            "National & international current affairs",
          ],
        },
      ],
    },
    {
      slug: "middle-6-8",
      name: "Classes 6–8 (Middle School)",
      audience: "Upper primary / Middle school teacher recruitment",
      subjects: [
        {
          name: "Mathematics & Science",
          description: "Combined middle school track covering secondary maths, physics, chemistry, and biology",
          topics: [
            "Number systems, algebra & linear equations",
            "Geometry, triangles, circles & mensuration",
            "Data handling & statistics",
            "Matter, physical/chemical changes & atomic structure",
            "Force, motion, work & energy",
            "Cell biology, plant & human physiology",
            "Ecosystem & environmental conservation",
          ],
        },
        {
          name: "Social Science",
          description: "History, Geography, Political Science, and Economics for Classes 6–8",
          topics: socialScience,
        },
        {
          name: "Languages",
          description: "Hindi, Urdu, Sanskrit, and English language options",
          topics: languages,
        },
      ],
    },
    {
      slug: "secondary-9-10",
      name: "Classes 9–10 (Secondary TGT)",
      audience: "Secondary school teacher recruitment (TGT)",
      subjects: [
        {
          name: "Mathematics",
          description: "Secondary mathematics at graduation depth covering algebra, geometry, trigonometry, and calculus basics",
          topics: [
            "Real numbers & polynomials",
            "Pair of linear equations & quadratic equations",
            "Arithmetic progressions",
            "Coordinate geometry & conic basics",
            "Trigonometry & heights/distances",
            "Circles, constructions & areas",
            "Surface areas & volumes",
            "Statistics & probability",
          ],
        },
        {
          name: "Science",
          description: "Physics, Chemistry, and Biology at secondary/graduation level",
          topics: [
            "Motion, force & gravitation",
            "Work, energy & sound",
            "Electricity & magnetic effects of current",
            "Chemical reactions, acids, bases & salts",
            "Metals & non-metals, carbon compounds",
            "Life processes, control & coordination",
            "Reproduction, heredity & evolution",
            "Environment & natural resource management",
          ],
        },
        {
          name: "Social Science",
          description: "History, Geography, Political Science, and Economics",
          topics: socialScience,
        },
        {
          name: "Languages & Arts",
          description: "Hindi, Urdu, Sanskrit, English, Bangla, Maithili, Arabic, Persian, Fine Arts, Music & Dance",
          topics: languages,
        },
      ],
    },
    {
      slug: "higher-secondary-11-12",
      name: "Classes 11–12 (Higher Secondary PGT)",
      audience: "Post Graduate Teacher (PGT) recruitment across 33 official subjects",
      subjects: [
        {
          name: "Mathematics",
          description: "Higher secondary and postgraduate level mathematics (Calculus, Algebra, Coordinate Geometry, Vectors & Statistics)",
          topics: [
            "Sets, Relations & Functions",
            "Real Numbers & Complex Numbers",
            "Sequences, Series & Progression",
            "Permutations, Combinations & Binomial Theorem",
            "Matrices & Determinants",
            "Linear Equations & Inequalities",
            "Coordinate Geometry & Conic Sections (2D & 3D)",
            "Trigonometric Functions & Inverse Trigonometry",
            "Limits, Continuity & Differentiability",
            "Applications of Derivatives (Tangents, Maxima/Minima)",
            "Integration, Definite Integrals & Differential Equations",
            "Vectors & Three-Dimensional Geometry",
            "Statistics, Probability Distributions & Numerical Methods",
          ],
        },
        {
          name: "Physics",
          description: "Mechanics, Thermodynamics, Electromagnetism, Optics, Modern Physics, and Practical Measurements",
          topics: [
            "Units, Measurement, Vectors & Errors",
            "Kinematics & Newton's Laws of Motion",
            "Work, Energy, Power & Circular/Rotational Motion",
            "Gravitation & Planetary Motion",
            "Properties of Bulk Matter, Fluids & Elasticity",
            "Thermodynamics, Heat & Kinetic Theory of Gases",
            "Oscillations, Waves & Acoustics",
            "Electrostatics, Electric Potential & Capacitance",
            "Current Electricity, Circuits & Kirchhoff's Laws",
            "Magnetic Effects of Current & Magnetism",
            "Electromagnetic Induction & Alternating Current",
            "Electromagnetic Waves & Ray/Wave Optics",
            "Dual Nature of Radiation, Atoms & Radioactivity",
            "Semiconductor Electronics & Digital Logic",
          ],
        },
        {
          name: "Chemistry",
          description: "Physical, Inorganic, Organic, Biomolecules, and Analytical/Practical Chemistry",
          topics: [
            "Mole Concept, Stoichiometry & Atomic Structure",
            "Chemical Bonding & Molecular Orbital Theory",
            "States of Matter & Chemical Thermodynamics",
            "Chemical Equilibrium & Ionic Equilibrium",
            "Redox Reactions & Electrochemistry",
            "Solutions, Colligative Properties & Chemical Kinetics",
            "Surface Chemistry & Metallurgy Principles",
            "Periodic Properties: s, p, d, and f Block Elements",
            "Coordination Compounds & Organometallics",
            "Hydrocarbons & Halogenated Derivatives",
            "Alcohols, Phenols & Ethers",
            "Aldehydes, Ketones & Carboxylic Acids",
            "Amines, Diazonium Salts & Nitrogen Compounds",
            "Biomolecules, Polymers & Chemistry in Everyday Life",
            "Practical & Qualitative Analysis Techniques",
          ],
        },
        {
          name: "Botany",
          description: "Plant diversity, morphology, anatomy, physiology, genetics, biotechnology, and economic botany",
          topics: [
            "Plant Diversity: Algae, Bryophytes, Pteridophytes, Gymnosperms & Angiosperms",
            "Plant Morphology, Tissues & Anatomy",
            "Cell Biology, Biomolecules & Enzymes",
            "Plant Physiology: Water Transport & Mineral Nutrition",
            "Photosynthesis & Plant Respiration",
            "Plant Growth Regulators & Phytohormones",
            "Plant Reproduction & Embryology",
            "Mendelian Genetics & Molecular Biology",
            "Plant Biotechnology & Tissue Culture",
            "Economic Botany, Plant Breeding & Pathology",
            "Ecology, Plant Geography & Biodiversity Conservation",
          ],
        },
        {
          name: "Zoology",
          description: "Animal diversity, human physiology, cell biology, genetics, evolution, and applied parasitology",
          topics: [
            "Non-Chordates & Chordates Diversity & Classification",
            "Structural Organisation in Animals & Tissues",
            "Cell Biology, Molecular Genetics & Chromosomes",
            "Human Physiology: Digestion, Respiration & Circulation",
            "Excretion, Muscle Locomotion & Skeletal System",
            "Neural Control, Sense Organs & Endocrine Regulation",
            "Human Reproduction & Embryonic Development",
            "Evolutionary Biology & Animal Behaviour (Ethology)",
            "Ecology, Wildlife Conservation & Environmental Biology",
            "Applied Zoology: Sericulture, Apiculture, Aquaculture & Parasitology",
            "Immunology, Vaccines & Human Diseases",
          ],
        },
        {
          name: "Computer Science",
          description: "Computer architecture, OOP programming, Data Structures, Relational DBMS, Networking, AI & Cybersecurity",
          topics: [
            "Computer Fundamentals, OS & Boolean Logic",
            "Number Systems & Data Representation",
            "Programming in Python & C++ (Syntax, Functions, Modules)",
            "Object-Oriented Programming (Classes, Inheritance, Polymorphism)",
            "Data Structures: Stacks, Queues, Linked Lists & Trees",
            "Searching & Sorting Algorithms (Complexity Analysis)",
            "Relational Database Model & SQL (DDL, DML, Joins)",
            "Database Normalisation (1NF, 2NF, 3NF, BCNF) & Transactions",
            "Computer Networks: OSI/TCP-IP, Routing & Protocols",
            "Web Technologies, HTML/CSS, JS & Web Security",
            "Cybersecurity, Encryption, Ethics & Cyber Laws",
            "Emerging Tech: Cloud Computing, IoT, Machine Learning & AI",
          ],
        },
        {
          name: "History",
          description: "Ancient, Medieval, Modern Indian History, Bihar's role in freedom movement, and World History",
          topics: [
            "Sources, Prehistory & Indus Valley Civilisation",
            "Vedic Culture, Mahajanapadas & Heterodox Sects (Buddhism/Jainism)",
            "Mauryan Empire, Post-Mauryan Era & Gupta Golden Age",
            "Harshavardhana, Early Medieval Dynasties & South Indian Kingdoms",
            "Delhi Sultanate Administration, Economy & Culture",
            "Mughal Empire: Akbar, Administration, Architecture & Decline",
            "Vijayanagara & Bahmani Kingdoms, Bhakti & Sufi Movements",
            "Colonial Expansion, 1857 Revolt & Socio-Religious Reforms",
            "Rise of Indian Nationalism & Formation of INC",
            "Gandhian Movements: Champaran, Non-Cooperation, Civil Disobedience, Quit India",
            "Bihar's Role in National Movement, Peasant & Tribal Uprisings",
            "Constitutional Reforms, Partition & Independence",
            "World History: Renaissance, Industrial Revolution, World Wars, Decolonisation",
          ],
        },
        {
          name: "Geography",
          description: "Physical geography, geomorphology, climatology, Indian geography, human geography, and GIS",
          topics: [
            "Solar System, Earth's Origin, Structure & Plate Tectonics",
            "Geomorphic Processes, Landforms, Rocks & Volcanoes",
            "Atmosphere: Structure, Insolation, Pressure Belts & Winds",
            "Climatology: Monsoons, Cyclones & Koppen Classification",
            "Oceanography: Relief, Temperature, Salinity, Tides & Currents",
            "Physiographic Divisions of India & River Drainage Systems",
            "Indian Climate, Soils, Natural Vegetation & Wildlife",
            "Agriculture, Crop Patterns, Irrigation & Mineral Resources",
            "Human Geography: Population Distribution, Migration & Urbanisation",
            "Economic Geography: Industries, Trade, Transport & Regional Planning",
            "Environmental Ecology, Natural Hazards & Disaster Management",
            "Cartography, Topographical Maps, Remote Sensing & GIS Basics",
          ],
        },
        {
          name: "Political Science",
          description: "Political theory, Indian Constitution, institutions, governance, international relations, and thinkers",
          topics: [
            "Political Theory: State, Sovereignty, Liberty, Equality & Justice",
            "Rights, Citizenship, Democracy, Nationalism & Secularism",
            "Making & Philosophy of the Indian Constitution",
            "Preamble, Fundamental Rights, Fundamental Duties & DPSP",
            "Union & State Executive: President, Prime Minister, Governor, CM",
            "Union & State Legislature: Parliament & State Assemblies",
            "Judiciary: Supreme Court, High Courts, Judicial Review & PIL",
            "Indian Federalism, Centre-State Relations & Local Self-Government",
            "Elections, Election Commission & Political Parties in India",
            "Comparative Politics, Constitutional Models & Political Systems",
            "International Relations: Globalisation, UN, Foreign Policy & Global Issues",
            "Political Thinkers: Western (Plato to Marx) & Indian (Kautilya, Gandhi, Ambedkar)",
          ],
        },
        {
          name: "Economics",
          description: "Microeconomics, Macroeconomics, Indian Economy, Public Finance, Money & Banking, and Statistics",
          topics: [
            "Consumer Behaviour, Utility, Demand Analysis & Elasticity",
            "Theory of Production, Cost Concepts & Revenue",
            "Market Structures: Perfect Competition, Monopoly & Monopolistic",
            "National Income Accounting & Measurement",
            "Classical & Keynesian Macroeconomics, Aggregate Demand/Supply",
            "Money, Banking, RBI Monetary Policy & Commercial Banks",
            "Inflation, Unemployment & Business Cycles",
            "Public Finance, Budget, Taxation & Fiscal Policy",
            "Indian Economy: Agriculture, Industry, Services & Infrastructure",
            "Poverty, Inequality, Human Development & NITI Aayog Planning",
            "Economic Reforms (1991), Liberalisation, Privatisation & Globalisation",
            "International Trade, Balance of Payments & Exchange Rates",
            "Statistics for Economics: Measures of Central Tendency & Dispersion",
          ],
        },
        {
          name: "Hindi",
          description: "Hindi language comprehension, vyakaran, kavya shastra, sahitya itihas, and prescribed authors",
          topics: [
            "Comprehension of unseen prose & poetry passages",
            "Hindi Vyakaran: Sandhi, Samasa, Sangya, Sarvanam, Visheshan, Kriya, Karak",
            "Linga, Vachan, Kaal, Vachya & Vakya Shuddhi",
            "Shabda Bhandar: Paryayvachi, Vilom, Anekarthi, Muhavare & Lokoktiyan",
            "Kavya Shastra: Rasa, Chhand, Alankar & Kavyaguna",
            "Hindi Sahitya Ka Itihas: Adikal, Bhaktikal, Ritikal, Adhunikkal",
            "Major Literary Movements: Chhayavad, Pragativad, Prayogvad, Nayi Kavita",
            "Major Hindi Authors & Prescribed NCERT/SCERT Prose and Poetry",
            "Bhasha Vigyan, Hindi Bhasha Ka Vikas & Devnagari Lipi",
          ],
        },
        {
          name: "English",
          description: "Reading comprehension, advanced grammar, literary periods, figures of speech, and writing skills",
          topics: [
            "Advanced Reading Comprehension (Factual, Literary & Discursive)",
            "Parts of Speech & Advanced Error Detection",
            "Tenses, Subject-Verb Agreement & Conditionals",
            "Active/Passive Voice & Direct/Indirect Speech",
            "Clauses, Sentence Synthesis & Degrees of Comparison",
            "Vocabulary: Synonyms, Antonyms, Idioms, Phrasal Verbs & One-Word Substitutes",
            "Literary Terms, Metre, Rhyme & Poetic Devices",
            "History of English Literature: Elizabethan, Romantic, Victorian, Modern",
            "Major Writers & Prescribed Works (Shakespeare, Milton, Wordsworth, Keats, Shaw)",
            "Functional Writing: Précis, Letter/Application, Essay & Paragraph Writing",
          ],
        },
        {
          name: "Urdu",
          description: "Urdu grammar, comprehension, prose, poetry, Ghazal, Nazm, Marsiya, and literary history",
          topics: [
            "Reading Comprehension & Prose/Poetry Interpretation",
            "Urdu Grammar: Ism, Zameer, Sifat, Fe'l, Mutazaad, Mutaradif",
            "Gender, Number, Tense, Voice & Sentence Correction",
            "Urdu Poetics: Sanaye-Badaye, Qafiya, Radeef, Bahr",
            "Literary Forms: Ghazal, Nazm, Qasida, Marsiya, Masnavi, Dastaan, Afsana",
            "History of Urdu Literature: Fort William College, Aligarh Movement, Progressive Writers",
            "Prominent Urdu Poets & Writers (Ghalib, Mir, Iqbal, Premchand, Faiz)",
          ],
        },
        {
          name: "Bengali",
          description: "Bengali language, grammar, literary history, and major literary works",
          topics: [
            "Reading Comprehension of Bengali Prose & Poetry",
            "Bengali Grammar: Sandhi, Samas, Karak, Bibhakti, Pad Parivartan",
            "Vocabulary: Samarthak, Biparitarthak Shabda, Bagdhara & Proverbs",
            "History of Bengali Literature: Ancient, Medieval (Charyapada, Mangalkavya) & Modern",
            "Prominent Authors: Rabindranath Tagore, Bankim Chandra, Sarat Chandra, Nazrul Islam",
          ],
        },
        {
          name: "Maithili",
          description: "Maithili grammar, vocabulary, folk literature, and classical/modern poetry and prose",
          topics: [
            "Maithili Grammar: Word Formation, Case, Tense & Sentence Structure",
            "Comprehension & Textual Analysis of Maithili Literature",
            "Maithili Folk Literature, Songs, Lore & Cultural Traditions",
            "Classical Maithili Literature: Mahakavi Vidyapati & Medieval Period",
            "Modern Maithili Literature, Major Dramas, Novels & Poets",
          ],
        },
        {
          name: "Sanskrit",
          description: "Classical Sanskrit grammar, translation, Vedic/Classical literature, and poetics",
          topics: [
            "Sanskrit Vyakaran: Dhatu Roop, Shabda Roop, Sandhi, Samasa, Pratyaya",
            "Karak Prakaran, Vibhakti Rules & Avyaya Usage",
            "Translation from Hindi/English to Sanskrit & Sanskrit to Hindi/English",
            "Unseen Prose & Shloka Comprehension",
            "Vedic Literature Overview & Upanishadic Shlokas",
            "Classical Sanskrit Authors & Works: Kalidasa, Bhasa, Bhavabhuti, Banabhatta",
            "Sanskrit Poetics, Chhanda & Alankaras",
          ],
        },
        {
          name: "Business Studies",
          description: "Management principles, business environment, corporate finance, marketing, and consumer protection",
          topics: [
            "Nature & Significance of Management, Management as Science/Art",
            "Principles of Management: Fayol's & Taylor's Scientific Principles",
            "Business Environment: Economic, Social, Technological & Legal Dimensions",
            "Functions of Management: Planning, Organising, Staffing, Directing & Controlling",
            "Financial Management: Investment, Financing & Dividend Decisions",
            "Financial Markets: Money Market, Capital Market, Primary & Secondary Markets",
            "Marketing Management: Product, Price, Place, Promotion & Digital Channels",
            "Consumer Protection Act & Consumer Rights",
            "Business Ethics, Corporate Social Responsibility & Emerging Trends",
          ],
        },
        {
          name: "Accountancy",
          description: "Accounting principles, partnership, company accounts, financial statements, and ratios",
          topics: [
            "Theoretical Framework of Accounting, GAAP & Accounting Standards",
            "Accounting Process: Journal, Ledger, Trial Balance & Bank Reconciliation",
            "Depreciation, Provisions, Reserves & Rectification of Errors",
            "Accounting for Partnership: Fundamentals, Goodwill Valuation & Reconstitution",
            "Partnership Accounts: Admission, Retirement, Death & Dissolution",
            "Company Accounts: Accounting for Share Capital (Issue, Forfeiture, Reissue)",
            "Accounting for Debentures: Issue & Redemption",
            "Financial Statements of a Company & Tools of Financial Analysis",
            "Accounting Ratios: Liquidity, Solvency, Activity & Profitability Ratios",
            "Cash Flow Statement (AS-3 compliant)",
            "Computerised Accounting Systems & Tally Basics",
          ],
        },
        {
          name: "Sociology",
          description: "Sociological concepts, social institutions, Indian social structure, stratification, and social change",
          topics: [
            "Nature & Scope of Sociology, Basic Concepts (Society, Community, Culture)",
            "Social Institutions: Family, Kinship, Marriage, Religion, Education & Economy",
            "Social Stratification: Caste, Class, Tribe, Gender & Power Dynamics",
            "Social Processes: Socialisation, Social Control, Cooperation, Conflict & Competition",
            "Indian Society: Unity in Diversity, Tribal Communities & Rural/Urban Social Structure",
            "Social Change: Industrialisation, Urbanisation, Modernisation & Westernisation",
            "Social Problems in India: Poverty, Unemployment, Communalism, Casteism & Gender Bias",
            "Sociological Thinkers: Comte, Marx, Durkheim, Weber, Ghurye & Srinivas",
            "Sociological Research Methods, Observation, Survey & Interview Techniques",
          ],
        },
        {
          name: "Psychology",
          description: "General psychology, cognition, personality, developmental psychology, and therapeutic applications",
          topics: [
            "Historical Foundations & Methods of Psychology",
            "Biological Bases of Behaviour: Nervous System, Brain & Endocrine System",
            "Sensory Processes, Perception, Attention & Consciousness",
            "Learning Principles: Classical Conditioning, Operant Conditioning & Cognitive Learning",
            "Human Memory: Encoding, Storage, Retrieval & Forgetting",
            "Thinking, Problem Solving, Language & Creativity",
            "Motivation, Emotion, Stress & Coping Mechanisms",
            "Human Intelligence: Theories, Assessment & Emotional Intelligence",
            "Personality Theories (Psychodynamic, Trait, Humanistic) & Assessment",
            "Lifespan Human Development: Infancy to Old Age",
            "Psychological Disorders, Classification (DSM) & Psychotherapeutic Approaches",
          ],
        },
        {
          name: "Philosophy",
          description: "Indian and Western philosophical systems, logic, epistemology, and moral/social philosophy",
          topics: [
            "Indian Philosophy: Vedic/Upanishadic Thought, Carvaka, Jainism & Buddhism",
            "Orthodox Indian Schools: Nyaya, Vaisheshika, Samkhya, Yoga, Mimamsa & Vedanta",
            "Western Philosophy: Greek (Socrates, Plato, Aristotle), Rationalism & Empiricism",
            "Critical Philosophy of Kant, Hegel, Existentialism & Pragmatism",
            "Epistemology: Sources of Valid Knowledge (Pramanas), Truth & Belief",
            "Logic: Deductive & Inductive Reasoning, Syllogisms & Fallacies",
            "Ethics: Moral Concepts, Duty, Consequentialism, Virtue Ethics & Applied Ethics",
            "Social & Political Philosophy: Rights, Justice, Equality, Liberty & Secularism",
          ],
        },
        {
          name: "Home Science",
          description: "Food & nutrition, human development, textiles, resource management, and extension communication",
          topics: [
            "Food Science, Nutrients, Balanced Diet & Meal Planning Across Lifespan",
            "Nutritional Deficiency Disorders, Therapeutic Nutrition & Food Preservation",
            "Human Growth & Development: Prenatal, Childhood, Adolescence & Adulthood",
            "Family Dynamics, Child Rearing, Guidance & Counseling",
            "Textiles: Fibre Classification, Yarn Processing, Fabric Construction & Finishes",
            "Apparel Design, Clothing Care & Laundry Methods",
            "Family Resource Management: Time, Energy, Money & Space Planning",
            "Consumer Education, Rights, Responsibilities & Redressal Mechanisms",
            "Extension Education, Community Development & Audio-Visual Communication",
          ],
        },
        {
          name: "Music",
          description: "Indian classical music, ragas, talas, gharanas, history, notation, and musical aesthetics",
          topics: [
            "Fundamental Concepts: Swara, Shruti, Saptak, Thaat, Raga, Tala, Laya, Matra",
            "Vocal & Instrumental Music Traditions of India",
            "Study of Prescribed Ragas (Aroha, Avroha, Pakad, Bandish & Vadi/Samvadi)",
            "Study of Prescribed Talas (Teental, Ektaal, Jhaptaal, Rupak, Dadra, Keharwa)",
            "Gharanas of Hindustani Music: Gwalior, Agra, Kirana, Jaipur, Patiala",
            "History of Indian Music: Ancient, Medieval, Modern & Musicologists (Pt. Bhatkhande, Pt. Paluskar)",
            "Classification of Musical Instruments (Tata, Sushira, Avanaddha, Ghana)",
            "Notation Systems of Bhatkhande & Paluskar",
          ],
        },
        {
          name: "Fine Arts",
          description: "Principles of art, drawing, painting, Indian art history, and art appreciation",
          topics: [
            "Elements of Art: Line, Form, Colour, Tone, Texture & Space",
            "Principles of Composition: Unity, Harmony, Balance, Rhythm & Proportion",
            "Drawing & Painting Techniques: Still Life, Nature Study, Perspective & Anatomy",
            "Mediums & Materials: Water Colour, Oil, Acrylic, Tempera, Fresco & Printmaking",
            "Prehistoric & Indus Valley Art, Mauryan, Ajanta & Ellora Sculptures/Murals",
            "Medieval Art: Miniature Paintings (Mughal, Rajasthani, Pahari & Deccani Schools)",
            "Modern Indian Art: Company School, Bengal School, Progressive Artists Group",
            "Folk & Tribal Art Traditions of India (Madhubani/Mithila, Warli, Pattachitra)",
          ],
        },
        {
          name: "Dance",
          description: "Indian classical dances, folk traditions, Abhinaya, talas, and dance history",
          topics: [
            "Elements of Dance: Nritta, Nritya, Natya, Tala, Laya & Rasa Theory",
            "Classical Dance Forms: Kathak, Bharatanatyam, Odissi, Kathakali, Manipuri, Kuchipudi, Mohiniyattam, Sattriya",
            "Natyashastra & Abhinaya Darpana Traditions",
            "Angika, Vachika, Aharya & Sattvika Abhinaya",
            "Folk & Tribal Dances of Bihar (Jhajhari, Jat-Jatin, Bidesia, Chhau) & India",
            "Famous Dancers, Gurus & Contemporary Developments in Dance",
          ],
        },
        {
          name: "Physical Education",
          description: "Anatomy, exercise physiology, sports training, yoga, nutrition, and sports psychology",
          topics: [
            "Concept, Objectives & Scope of Physical Education",
            "Anatomy & Physiology: Muscular, Skeletal, Circulatory & Respiratory Systems",
            "Exercise Physiology: Aerobic/Anaerobic Capacity & Effects of Training",
            "Sports Training: Principles, Periodisation, Strength, Speed, Endurance & Flexibility",
            "Rules, Skills, Field Markings & Officiating of Major Games & Sports",
            "Yoga: Asanas, Pranayama, Kriyas & Health Benefits",
            "Sports Nutrition, Balanced Diet, Ergogenic Aids & Weight Management",
            "Sports Injuries, Prevention, First Aid & Rehabilitation",
            "Sports Psychology: Motivation, Anxiety, Aggression & Personality",
            "Measurement, Evaluation & Fitness Testing Protocols",
          ],
        },
        {
          name: "Entrepreneurship",
          description: "Entrepreneurial mindset, business opportunities, project planning, resource mobilization, and enterprise management",
          topics: [
            "Entrepreneurship: Concept, Functions, Types & Need in Economic Development",
            "Entrepreneurial Motivation, Competencies & Opportunity Sensing",
            "Business Idea Generation, Feasibility Study & Environmental Scanning",
            "Business Plan: Operational, Financial, Marketing & Human Resource Plans",
            "Forms of Business Organisation: Sole Proprietorship, Partnership, LLP & Company",
            "Resource Mobilisation: Capital Requirements, Debt, Equity, Angels & VC Funding",
            "Marketing Strategy: Market Research, Pricing, Branding & Salesmanship",
            "Financial Management: Cash Flow, Break-Even Analysis & Working Capital",
            "Legal & Regulatory Requirements: GST, Intellectual Property Rights (IPR), Patents & Trademarks",
            "Enterprise Growth Strategies, Franchising & Social Entrepreneurship",
          ],
        },
        {
          name: "Arabic",
          description: "Arabic language grammar, comprehension, vocabulary, and classical/modern literature",
          topics: [
            "Reading Comprehension of Classical & Modern Arabic Prose and Poetry",
            "Arabic Morphology (Sarf) & Syntax (Nahw)",
            "Noun & Verb Conjugation, Tenses, Pronouns, Gender & Number",
            "Translation from Arabic to English/Hindi and vice-versa",
            "History of Arabic Literature: Pre-Islamic, Islamic, Abbasid & Modern Periods",
          ],
        },
        {
          name: "Persian",
          description: "Persian grammar, comprehension, vocabulary, idioms, and literary traditions",
          topics: [
            "Reading Comprehension of Persian Prose & Poetry Texts",
            "Persian Grammar: Dastoor, Verbs (Masdar), Tenses, Nouns & Adjectives",
            "Sentence Construction, Idioms, Proverbs & Translation",
            "History of Persian Literature: Classical Poets (Saadi, Hafez, Rumi, Firdausi)",
            "Indo-Persian Literature: Amir Khusro, Faizi, Ghalib & Mughal Court Historians",
          ],
        },
        {
          name: "Bhojpuri",
          description: "Bhojpuri language grammar, folk literature, idioms, and cultural heritage",
          topics: [
            "Bhojpuri Grammar, Phonology & Sentence Structure",
            "Bhojpuri Vocabulary, Idioms, Sayings & Expressions",
            "Folk Literature: Lokgeet, Birha, Kajri, Sohar, Chhath Geet & Lore",
            "Bhojpuri Theater & Literary Works of Bhikhari Thakur",
            "Modern Bhojpuri Literature, Prose, Poetry & Drama",
          ],
        },
        {
          name: "Magahi",
          description: "Magahi grammar, vocabulary, oral traditions, and literature",
          topics: [
            "Magahi Grammar, Sound Systems & Syntax",
            "Magahi Vocabulary & Idiomatic Usages",
            "Magahi Folk Literature, Lorikayan, Ballads & Oral Traditions",
            "Modern Magahi Prose, Poetry, Short Stories & Major Writers",
          ],
        },
        {
          name: "Pali",
          description: "Pali language, grammar, Tripitaka literature, and Buddhist texts",
          topics: [
            "Pali Grammar: Sandhi, Nouns, Verbs, Cases & Compounds",
            "Translation & Comprehension of Pali Passages",
            "Tripitaka Tradition: Vinaya Pitaka, Sutta Pitaka & Abhidhamma Pitaka",
            "Dhammapada, Jataka Tales & Major Commentaries",
            "History of Pali Language, Literature & Ashokan Inscriptions",
          ],
        },
        {
          name: "Prakrit",
          description: "Prakrit languages, grammar, morphology, Jain literature, and historical linguistics",
          topics: [
            "Prakrit Grammar, Morphology, Phonetics & Morpho-Syntax",
            "Translation & Textual Comprehension of Prakrit Verses",
            "Jain Agamas, Sacred Texts & Canonical Literature",
            "Major Prakrit Dialects: Ardhamagadhi, Shauraseni, Maharashtri & Paisachi",
            "Evolution from Prakrit to Apabhramsha and Modern Indo-Aryan Languages",
          ],
        },
      ],
    },
  ],
  "bihar-stet": [
    {
      slug: "paper-1-9-10",
      name: "Paper I · Classes 9–10",
      audience: "Secondary teacher eligibility (STET Paper I)",
      subjects: [
        {
          name: "Languages",
          description: "Hindi, Urdu, Bangla, Maithili, Sanskrit, Arabic, Persian, Bhojpuri and English",
          topics: languages.concat(["Translation", "Prosody & poetics"]),
        },
        {
          name: "Mathematics",
          description: "Paper I subject preparation at the applicable graduation level",
          topics: ["Real numbers & algebra", "Geometry & trigonometry", "Calculus foundations", "Statistics & probability", "Coordinate geometry"],
        },
        {
          name: "Science",
          description: "Physics, chemistry, biology and environmental science",
          topics: ["Mechanics & electricity", "Matter & chemical reactions", "Cell, genetics & physiology", "Ecology & conservation"],
        },
        {
          name: "Social Science",
          description: "History, geography, political science and economics",
          topics: socialScience,
        },
        {
          name: "Arts & Physical Education",
          description: "Physical Education, Music, Fine Arts and Dance",
          topics: ["Theory & foundations", "History & traditions", "Practice terminology", "Health, training & evaluation"],
        },
        {
          name: "Teaching Art & Other Skills",
          description: "Common 50-mark component for all STET aspirants",
          topics: commonTeaching.concat(["Communication", "General knowledge", "Environmental science", "Mathematical aptitude", "Logical reasoning"]),
        },
      ],
    },
    {
      slug: "paper-2-11-12",
      name: "Paper II · Classes 11–12",
      audience: "Higher secondary teacher eligibility (STET Paper II)",
      subjects: [
        {
          name: "Languages",
          description: "Hindi, Urdu, English, Sanskrit, Bangla, Maithili, Magahi, Arabic, Persian, Bhojpuri, Pali and Prakrit",
          topics: languages.concat(["Linguistics", "Literary criticism", "Translation & poetics"]),
        },
        {
          name: "Science",
          description: "Mathematics, physics, chemistry, botany and zoology",
          topics: ["Advanced mathematics", "Mechanics, optics & modern physics", "Organic, inorganic & physical chemistry", "Plant biology", "Animal biology"],
        },
        {
          name: "Social Sciences",
          description: "History, geography, political science, economics, sociology, psychology and philosophy",
          topics: socialScience.concat(["Sociological theory", "Psychology", "Indian & western philosophy"]),
        },
        {
          name: "Computer Science",
          description: "Paper II subject code 226 (PGT Computer Science)",
          topics: ["Programming", "Data structures", "Operating systems", "DBMS & SQL", "Networks", "Security & cryptography", "AI & data mining"],
        },
        {
          name: "Commerce & Agriculture",
          description: "Commerce, home science and agriculture pathways",
          topics: ["Accounting & auditing", "Business management", "Nutrition & human development", "Agronomy", "Plant breeding & pathology"],
        },
        {
          name: "Teaching Art & Other Skills",
          description: "Common teaching and general skills component",
          topics: commonTeaching,
        },
      ],
    },
  ],
};

// ==========================================
// MOCK TESTS SPECIFICATION & CATALOG
// ==========================================
// 1. Non-VIP Free Users: Exactly 2 Free diagnostic full/core mocks (Unlimited repeat attempts)
// 2. VIP Users: Unlocked access to all full-length mocks, subject-specific mocks, and sectional tests

export const mockTests: MockTestItem[] = [
  // -------------------------------------------------------------
  // BPSC TRE 4.0: HIGHER SECONDARY (CLASSES 11-12) - FREE DIAGNOSTIC MOCKS (2 TESTS FOR NON-VIP)
  // -------------------------------------------------------------
  {
    slug: "bpsc-tre-4-11-12-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "All Subjects",
    name: "BPSC TRE 4.0 (11-12): All-Subject Full Diagnostic Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Free",
    type: "Full mock",
    description: "Full-length 150-question CBT exam simulation covering Part-I Language (30 Qs), Part-II General Studies (40 Qs), and Part-III Subject Foundation (80 Qs) with official 5-option format and negative marking.",
  },
  {
    slug: "bpsc-tre-4-11-12-common-foundation-mock",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "General Studies & Language",
    name: "BPSC TRE 4.0 (11-12): Core Foundation Mock (Language Part-I + GS Part-II)",
    questions: 70,
    duration: "70 min",
    access: "Free",
    type: "Section test",
    description: "Targeted 70-question practice for the mandatory common papers: 30 qualifying language questions (English + Hindi) and 40 common General Studies questions for all Class 11-12 PGT candidates.",
  },

  // -------------------------------------------------------------
  // BPSC TRE 4.0: HIGHER SECONDARY (CLASSES 11-12) - FULL LENGTH 150-Q SUBJECT MOCKS (VIP PASS)
  // -------------------------------------------------------------
  {
    slug: "bpsc-tre-4-11-12-computer-science-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Computer Science",
    name: "Computer Science (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Computer Science (Python/C++, Data Structures, DBMS, SQL, Computer Networks, OS & Cyber Security).",
  },
  {
    slug: "bpsc-tre-4-11-12-mathematics-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Mathematics",
    name: "Mathematics (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Advanced Mathematics (Calculus, Coordinate Geometry, Vectors, Algebra, Matrices & Probability).",
  },
  {
    slug: "bpsc-tre-4-11-12-physics-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Physics",
    name: "Physics (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Senior Secondary Physics (Mechanics, Thermodynamics, Electromagnetism, Optics & Modern Physics).",
  },
  {
    slug: "bpsc-tre-4-11-12-chemistry-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Chemistry",
    name: "Chemistry (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Chemistry (Physical, Inorganic, Organic, Biomolecules & Reaction Mechanisms).",
  },
  {
    slug: "bpsc-tre-4-11-12-botany-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Botany",
    name: "Botany (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Botany (Plant Diversity, Physiology, Photosynthesis, Genetics & Biotechnology).",
  },
  {
    slug: "bpsc-tre-4-11-12-zoology-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Zoology",
    name: "Zoology (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Zoology (Animal Diversity, Human Physiology, Genetics, Evolution & Applied Parasitology).",
  },
  {
    slug: "bpsc-tre-4-11-12-history-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "History",
    name: "History (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 History (Ancient India, Medieval Sultanate/Mughals, Modern Freedom Movement, Bihar History & World History).",
  },
  {
    slug: "bpsc-tre-4-11-12-geography-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Geography",
    name: "Geography (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Geography (Geomorphology, Climatology, Indian Physiography, Resource Distribution & Human Geography).",
  },
  {
    slug: "bpsc-tre-4-11-12-political-science-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Political Science",
    name: "Political Science (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Political Science (Political Theory, Indian Constitution, Federalism, IR & Western/Indian Thinkers).",
  },
  {
    slug: "bpsc-tre-4-11-12-economics-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Economics",
    name: "Economics (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Economics (Microeconomics, Macroeconomics, Indian Economy, Public Finance & Economic Statistics).",
  },
  {
    slug: "bpsc-tre-4-11-12-hindi-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Hindi",
    name: "Hindi Language & Literature (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Hindi Sahitya (Hindi Vyakaran, Kavya Shastra, Hindi Sahitya Ka Itihas & Prescribed Literature).",
  },
  {
    slug: "bpsc-tre-4-11-12-english-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "English",
    name: "English Language & Literature (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 English Literature (Reading Comprehension, Advanced Grammar, Literary Periods & Major Authors).",
  },
  {
    slug: "bpsc-tre-4-11-12-accountancy-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Accountancy",
    name: "Accountancy (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Accountancy (Partnership, Company Accounts, Cash Flow Statements, Ratios & GAAP).",
  },
  {
    slug: "bpsc-tre-4-11-12-business-studies-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Business Studies",
    name: "Business Studies (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Business Studies (Management Principles, Financial Markets, Marketing Mix & Consumer Protection).",
  },
  {
    slug: "bpsc-tre-4-11-12-sociology-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Sociology",
    name: "Sociology (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Sociology (Social Institutions, Indian Social Stratification, Social Change & Sociological Thinkers).",
  },
  {
    slug: "bpsc-tre-4-11-12-psychology-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Psychology",
    name: "Psychology (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Psychology (Cognition, Learning, Personality Assessment, Lifespan Development & Psychotherapy).",
  },
  {
    slug: "bpsc-tre-4-11-12-home-science-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Home Science",
    name: "Home Science (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Home Science (Food & Nutrition, Human Development, Textiles, Resource Management & Extension).",
  },
  {
    slug: "bpsc-tre-4-11-12-physical-education-full-mock-01",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Physical Education",
    name: "Physical Education (11-12): Full Length CBT Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Premium",
    type: "Full mock",
    description: "Complete 150-question mock: 30 Language + 40 GS + 80 Physical Education (Anatomy, Exercise Physiology, Sports Rules, Yoga & Sports Psychology).",
  },

  // -------------------------------------------------------------
  // BPSC TRE 4.0: HIGHER SECONDARY (CLASSES 11-12) - SUBJECT-WISE CONCERNED (80 QUESTIONS) TESTS
  // -------------------------------------------------------------
  ...[
    "Mathematics",
    "Physics",
    "Chemistry",
    "Botany",
    "Zoology",
    "Computer Science",
    "History",
    "Geography",
    "Political Science",
    "Economics",
    "Hindi",
    "English",
    "Urdu",
    "Bengali",
    "Maithili",
    "Sanskrit",
    "Business Studies",
    "Accountancy",
    "Entrepreneurship",
    "Sociology",
    "Psychology",
    "Philosophy",
    "Home Science",
    "Music",
    "Fine Arts",
    "Dance",
    "Physical Education",
    "Arabic",
    "Persian",
    "Bhojpuri",
    "Magahi",
    "Pali",
    "Prakrit",
  ].map((subj) => ({
    slug: `bpsc-tre-4-11-12-${subj.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-part3-test`,
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: subj,
    name: `${subj} (11-12): Part-III Concerned Subject 80-Q Test`,
    questions: 80,
    duration: "80 min",
    access: "Premium" as const,
    type: "Subject test" as const,
    description: `Intensive 80-question practice test covering all prescribed Part-III ${subj} syllabus topics for BPSC TRE 4.0 Higher Secondary (PGT).`,
  })),

  // -------------------------------------------------------------
  // BPSC TRE 4.0: SECTIONAL & TOPIC TESTS (LANGUAGE & GS SPRINTS)
  // -------------------------------------------------------------
  {
    slug: "bpsc-tre-4-11-12-maths-reasoning-sprint",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "General Studies",
    name: "General Studies: Elementary Maths & Mental Ability Sprint",
    questions: 40,
    duration: "40 min",
    access: "Premium",
    type: "Topic test",
    description: "40 focused questions on BODMAS, percentage, ratio, number system, series, blood relations, and logical reasoning.",
  },
  {
    slug: "bpsc-tre-4-11-12-inm-bihar-gk-sprint",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "General Studies",
    name: "General Studies: Indian National Movement & Bihar GK Sprint",
    questions: 40,
    duration: "40 min",
    access: "Premium",
    type: "Topic test",
    description: "40 high-weightage questions on 1857 Revolt, Gandhian movements, Bihar freedom fighters, Champaran Satyagraha, and state geography.",
  },
  {
    slug: "bpsc-tre-4-11-12-general-science-sprint",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "General Studies",
    name: "General Studies: General Science & Environmental Ecology Sprint",
    questions: 40,
    duration: "40 min",
    access: "Premium",
    type: "Topic test",
    description: "40 questions covering daily physics, common chemical reactions, human body systems, ecology, and environmental pollution.",
  },
  {
    slug: "bpsc-tre-4-11-12-language-qualifying-sprint",
    exam: "BPSC TRE 4.0",
    track: "Classes 11–12 (PGT)",
    subject: "Language (Qualifying)",
    name: "Language Qualifying Master: English + Hindi Sectional Test",
    questions: 30,
    duration: "30 min",
    access: "Premium",
    type: "Section test",
    description: "Official 30-question qualifying language simulation (8 English + 22 Hindi) testing comprehension, grammar, and vocabulary.",
  },

  // -------------------------------------------------------------
  // PRIMARY & MIDDLE TRACK MOCKS (CLASSES 1-5 & 6-8 & 9-10)
  // -------------------------------------------------------------
  {
    slug: "primary-1-5-language-mock",
    exam: "BPSC TRE 4.0",
    track: "Classes 1–5 (Primary)",
    subject: "Language",
    name: "Language (1–5): Full Diagnostic Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Free",
    type: "Full mock",
    description: "Diagnostic primary language mock covering English, Hindi, and Urdu language foundations.",
  },
  {
    slug: "primary-1-5-elementary-mathematics-mock",
    exam: "BPSC TRE 4.0",
    track: "Classes 1–5 (Primary)",
    subject: "Elementary Mathematics",
    name: "Elementary Mathematics (1–5): Focus Practice",
    questions: 40,
    duration: "40 min",
    access: "Premium",
    type: "Subject test",
    description: "Primary-level quantitative and data skills practice.",
  },
  {
    slug: "primary-1-5-general-studies-mock",
    exam: "BPSC TRE 4.0",
    track: "Classes 1–5 (Primary)",
    subject: "General Studies",
    name: "General Studies (1–5): Focus Practice",
    questions: 40,
    duration: "40 min",
    access: "Premium",
    type: "Subject test",
    description: "Core GS covering Bihar GK, science, and reasoning for primary teachers.",
  },
  {
    slug: "middle-6-8-mathematics-science-mock",
    exam: "BPSC TRE 4.0",
    track: "Classes 6–8 (Middle School)",
    subject: "Mathematics & Science",
    name: "Mathematics & Science (6–8): Full Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Free",
    type: "Full mock",
    description: "Full mock covering middle school mathematics, physical sciences, and biology.",
  },
  {
    slug: "secondary-9-10-mathematics-mock",
    exam: "BPSC TRE 4.0",
    track: "Classes 9–10 (Secondary TGT)",
    subject: "Mathematics",
    name: "Mathematics (9–10): Full Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Free",
    type: "Full mock",
    description: "Secondary mathematics mock with graduation-level preparation depth.",
  },
  {
    slug: "secondary-9-10-science-mock",
    exam: "BPSC TRE 4.0",
    track: "Classes 9–10 (Secondary TGT)",
    subject: "Science",
    name: "Science (9–10): Focus Practice",
    questions: 40,
    duration: "40 min",
    access: "Premium",
    type: "Subject test",
    description: "Physics, chemistry, and biology practice for secondary teacher recruitment.",
  },

  // -------------------------------------------------------------
  // BIHAR STET MOCKS
  // -------------------------------------------------------------
  {
    slug: "bihar-stet-paper-1-complete-mock",
    exam: "Bihar STET",
    track: "Paper I · Classes 9–10",
    subject: "Teaching Art & Other Skills",
    name: "Paper I: Complete Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Free",
    type: "Full mock",
    description: "Complete STET Paper I simulation with pedagogy and subject questions.",
  },
  {
    slug: "bihar-stet-paper-2-computer-science-mock",
    exam: "Bihar STET",
    track: "Paper II · Classes 11–12",
    subject: "Computer Science",
    name: "Computer Science (STET Paper II): Full Mock 01",
    questions: 150,
    duration: "150 min",
    access: "Free",
    type: "Full mock",
    description: "STET Paper II Subject Code 226 Computer Science full length mock test.",
  },
];
